version: "3"
    
volumes:
    volume-mariaDB:
    
services:
    db:
        image: mariadb:10.7.1-focal
        container_name: tp3-DB
        ports:
          - 3306:3306
        volumes:
            - ./Scripts/schema.sql:/docker-entrypoint-initdb.d/init-script.sql
        environment:
            MARIADB_USER: tp3user
            MARIADB_PASSWORD: BUufjwennjen8920
            MARIADB_DATABASE: tp3
            MARIADB_ROOT_PASSWORD: ThisBeRootPassword
        restart: always
    tp3-back:
        build: ./back
        container_name: tp3-back
        environment:
            - DB_HOST=tp3-DB
            - DB_USER=tp3user
            - DB_PASSWORD=BUufjwennjen8920
            - DB_PORT=3306
            - DB_NAME=tp3
        ports:
            - 8080:8080
        links:
            - tp3-DB
        depends_on:
            - tp3-DB
        
    tp3-front:
        build: ./front
        container_name: tp3-front
        links:
            - tp3-back
        depends_on:
            - tp3-back
        ports:
            - 4200:4200
